apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-pod-identifier
  labels:
    app: scalable-pod-identifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-pod-identifier
  template:
    metadata:
      labels:
        app: scalable-pod-identifier
    spec:
      containers:
        - name: scalable-pod-identifier
          image: docker.io/shestera/scaletestapp
          resources:
            limits:
              memory: "30Mi"
          ports:
            - containerPort: 8080

