apiVersion: v1
kind: Service
metadata:
  name: scalable-pod-identifier
  labels:
    app: scalable-pod-identifier
spec:
  selector:
    app: scalable-pod-identifier
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
